use_frameworks!

platform :ios, '12.0'

target 'MYIOSAdsSDK_Example' do
  pod 'MYIOSAdsSDK', :path => '../'
  
  pod 'Ads-CN-Beta', '~> 6.9.0.3', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'HRAdSDK/HR','1.7.19.0'
  pod 'WechatOpenSDK'
  pod 'KSCrash', '~> 1.17.7'
  pod 'BeiZiSDK-iOS/BeiZiSDK-iOS', '4.90.4.35'
  pod 'GDTMobSDK', '~> 4.15.40'
  pod 'KSAdSDK', '~> 3.3.76.5'
  pod 'QMAdSDK', '~> 1.3.4'
  pod 'JADYun', '2.6.8'
  pod 'UBiXMediationSDK', '2.8.1'
  pod 'UBiXMUBiXAdapter'

  target 'MYIOSAdsSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Masonry', 'MBProgressHUD'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
