use_frameworks!

platform :ios, '12.0'

target 'MYIOSAdsSDK_Example' do
  pod 'MYIOSAdsSDK', :path => '../'
  
  pod 'Ads-CN-Beta', '~> 6.8.0.4', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'KSAdSDK', '~> 3.3.75'
  pod 'GDTMobSDK', '~> 4.15.10'
  pod 'JADYun', '2.6.4'
  pod 'BeiZiSDK-iOS/BeiZiSDK-iOS', '4.90.4.30'
  pod 'HRAdSDK/HR','1.7.19.0'
  pod 'OctopusSDK', '1.6.2.13'
  pod "QuMengAdSDK", "1.3.4"
  
  pod 'WechatOpenSDK_UnPay'

  target 'MYIOSAdsSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Masonry', 'MBProgressHUD'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
