use_frameworks!

platform :ios, '12.0'

target 'MYIOSAdsSDK_Example' do
  pod 'MYIOSAdsSDK', :path => '../'
  
  pod 'Ads-CN-Beta','6.6.0.0', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'KSAdSDK', '3.3.69.3'
  pod 'GDTMobSDK', '4.14.90'
  pod 'JADYun', '2.6.6'
  pod 'BaiduMobAdSDK', '~> 5.371'
#  pod 'UBiXMerakSDK', '2.5.0'
#  pod 'UBiXMBaiduAdapter', '5.371.1'
  
  pod 'WechatOpenSDK_UnPay'
  pod 'CocoaAsyncSocket'
  pod 'SDWebImage'
  pod 'Masonry'

  target 'MYIOSAdsSDK_Tests' do
    inherit! :search_paths

    
  end
end
